window.MAP_PREVIEW = {
 "fps": 30,
 "frames": [
  {"file": "move_000.jpg", "phase": "대기"},
  {"file": "move_001.jpg", "phase": "대기"},
  {"file": "move_002.jpg", "phase": "대기"},
  {"file": "move_003.jpg", "phase": "대기"},
  {"file": "move_004.jpg", "phase": "대기"},
  {"file": "move_005.jpg", "phase": "대기"},
  {"file": "move_006.jpg", "phase": "대기"},
  {"file": "move_007.jpg", "phase": "대기"},
  {"file": "move_008.jpg", "phase": "대기"},
  {"file": "move_009.jpg", "phase": "대기"},
  {"file": "move_010.jpg", "phase": "대기"},
  {"file": "move_011.jpg", "phase": "대기"},
  {"file": "move_012.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_013.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_014.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_015.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_016.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_017.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_018.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_019.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_020.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_021.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_022.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_023.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_024.jpg", "phase": "점프"},
  {"file": "move_025.jpg", "phase": "점프"},
  {"file": "move_026.jpg", "phase": "점프"},
  {"file": "move_027.jpg", "phase": "점프"},
  {"file": "move_028.jpg", "phase": "점프"},
  {"file": "move_029.jpg", "phase": "점프"},
  {"file": "move_030.jpg", "phase": "점프"},
  {"file": "move_031.jpg", "phase": "점프"},
  {"file": "move_032.jpg", "phase": "점프"},
  {"file": "move_033.jpg", "phase": "점프"},
  {"file": "move_034.jpg", "phase": "점프"},
  {"file": "move_035.jpg", "phase": "점프"},
  {"file": "move_036.jpg", "phase": "점프"},
  {"file": "move_037.jpg", "phase": "점프"},
  {"file": "move_038.jpg", "phase": "점프"},
  {"file": "move_039.jpg", "phase": "점프"},
  {"file": "move_040.jpg", "phase": "점프"},
  {"file": "move_041.jpg", "phase": "점프"},
  {"file": "move_042.jpg", "phase": "점프"},
  {"file": "move_043.jpg", "phase": "점프"},
  {"file": "move_044.jpg", "phase": "점프"},
  {"file": "move_045.jpg", "phase": "점프"},
  {"file": "move_046.jpg", "phase": "점프"},
  {"file": "move_047.jpg", "phase": "점프"},
  {"file": "move_048.jpg", "phase": "점프"},
  {"file": "move_049.jpg", "phase": "점프"},
  {"file": "move_050.jpg", "phase": "점프"},
  {"file": "move_051.jpg", "phase": "동쪽으로 걷기"},
  {"file": "move_052.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_053.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_054.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_055.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_056.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_057.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_058.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_059.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_060.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_061.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_062.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_063.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_064.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_065.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_066.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_067.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_068.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_069.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_070.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_071.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_072.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_073.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_074.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_075.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_076.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_077.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_078.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_079.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_080.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_081.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_082.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_083.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_084.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_085.jpg", "phase": "남쪽으로 → 구멍 (2, 1)"},
  {"file": "move_086.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_087.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_088.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_089.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_090.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_091.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_092.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_093.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_094.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_095.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_096.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_097.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_098.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_099.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_100.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_101.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_102.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_103.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_104.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_105.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_106.jpg", "phase": "구멍으로 낙하"},
  {"file": "move_107.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_108.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_109.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_110.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_111.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_112.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_113.jpg", "phase": "낙하 (화면 밖)"},
  {"file": "move_114.jpg", "phase": "낙하 (화면 밖)"}
 ]
};
